# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm build
    - run: npm test faculty.test.js
    - run: sonar-scanner.bat -D"sonar.projectKey=SH" -D"sonar.sources=." -D"sonar.host.url=http://localhost:9000" -D"sonar.login=98656ce7263dc15f939f9a17ce39ebc974ed51cd"
      env:
        CI: true
